import Head from 'next/head'
import { PRODUCT_QUERY } from "../lib/query";
import { useQuery } from "urql";

export default function Home() {
  //fetch products from strapi
  const [result] = useQuery({query: PRODUCT_QUERY});
  console.log(result);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello nEXT</h1>
      </main>
    </div>
  )
}
